🚧 refactor: mobile-app-icon, footer-app
qiwi/pijma pull request #335
Opened 2020-10-09 10:08 UTC by Irinaa133

2020-10-09 10:09 UTC, Irinaa133 commented
![image](https://user-images.githubusercontent.com/33098238/95571157-ab163780-0a30-11eb-8e02-d1f2ba6bab76.png)
![image](https://user-images.githubusercontent.com/33098238/95571173-b1a4af00-0a30-11eb-9cea-371d40e6221f.png)

2020-10-09 10:33 UTC, antongolub approved these changes

2020-10-09 10:33 UTC, antongolub commented on packages/desktop/src/footer-app/FooterApp.md
> +      href: 'https://appgallery.huawei.com/#/app/C101130485',
//appgallery.

2020-10-09 11:36 UTC, antongolub approved these changes

2020-10-09 12:46 UTC, dimonka83 requested changes

2020-10-09 12:46 UTC, dimonka83 commented on packages/desktop/src/footer-app/FooterApp.md
> +      href: '//s.qiwi.com/2m3_GW1_z3V',
давайте прямую ссылку укажем, а то мало ли что

2020-10-09 12:46 UTC, dimonka83 commented on packages/desktop/src/footer-app/FooterApp.md
> +      href: '//bnc.lt/x0Ih/pNHp68DJ9s',
и тут

2020-10-15 17:29 UTC, dimonka83 requested changes

2020-10-15 17:29 UTC, dimonka83 commented on packages/core/src/icon/MobileAppIcon.tsx
> +      <mask
непонятно зачем тут маска, иконки же вроде монохромные?

2020-10-15 17:32 UTC, dimonka83 requested changes

2020-10-15 17:32 UTC, dimonka83 commented on packages/core/src/icon/MobileAppIcon.tsx
> +      <mask
ну или если нужен, то id нужны "нормальные", а не просто "а"

2020-10-16 13:01 UTC, closed without merging