🚧 fix: load cashed image
qiwi/pijma pull request #336
Opened 2020-10-12 07:22 UTC by AlekseyShatohin

2020-10-12 15:06 UTC, antongolub approved these changes

2020-10-12 18:04 UTC, dimonka83 requested changes

2020-10-13 14:08 UTC, dimonka83 requested changes

2020-10-14 16:13 UTC, dimonka83 commented on packages/core/src/image/ImageControl.ts
> +  private onLoad: () => void = () => {
давай выше к остальным хэндлерами

2020-10-14 16:14 UTC, dimonka83 commented on packages/core/src/image/ImageControl.ts
> +      this.image.srcset = this.props.srcSet ? this.props.srcSet : ''
зачем тернарка?

2020-10-15 07:06 UTC, dimonka83 requested changes

2020-10-15 07:06 UTC, dimonka83 commented on packages/core/src/image/ImageControl.ts
> +        this.image.src = ''
не понимаю почему тут "останавливаем" проверку на закешированность? вроде надо в cached таймере

2020-10-15 07:06 UTC, dimonka83 commented on packages/core/src/image/ImageControl.ts
> +    if (this.state.cached === undefined) {
имхо, тут !this.state.cached

2020-10-15 07:06 UTC, dimonka83 commented on packages/core/src/image/ImageControl.ts
> +      this.image = document.createElement('img')
создание img надо тоже в cached таймер засунуть, даже this.image не нужен будет

2020-10-15 07:33 UTC, AlekseyShatohin commented on packages/core/src/image/ImageControl.ts
> +    if (this.state.cached === undefined) {
У `cached` 3 состояния: `undefined` - никогда не проверяли кэш, `true` - в кэше и `false` - не в кэше. Если как ты говоришь, то тогда и на `false` будет проходить условие и постоянно будем проверять уже проверенное изображение

2020-10-16 09:10 UTC, dimonka83 requested changes

2020-10-16 09:10 UTC, dimonka83 commented on packages/core/src/image/ImageControl.ts
> +  cache: boolean | undefined
давай один стейт: 'VIEW', 'LOAD', 'DONE' и т.д.

2020-10-16 13:01 UTC, dimonka83 approved these changes

2020-10-16 13:02 UTC, merged