feat: stub for suggest field
qiwi/pijma pull request #431
Opened 2021-08-06 14:42 UTC by AlekseyShatohin

2021-08-06 14:44 UTC, AlekseyShatohin commented on packages/desktop/src/suggest-field/SuggestField.tsx
> +                                          src={renderProps.items[key].stub!}
ts почему-то не видит, что выше есть проверка на undefined. Поэтому, пришлось поставить !

2021-08-06 14:49 UTC, Irinaa133 commented on packages/mobile/src/suggest-field/SuggestField.tsx
> +                                      true
почему stub true по умолчанию?

2021-08-06 14:51 UTC, AlekseyShatohin commented on packages/mobile/src/suggest-field/SuggestField.tsx
> +                                      true
Ну чтоб если не передававали стаб, то оставить дэфолтное поведение

2021-08-06 14:53 UTC, Irinaa133 commented
название не соответствует содержимому, тут стаб для лого элементов поиска

2021-08-06 14:53 UTC, AlekseyShatohin commented on packages/mobile/src/suggest-field/SuggestField.tsx
> +                                      true
У <Image/> stub={true} по умолчанию

2021-08-06 14:54 UTC, snoosmoomrik commented on packages/desktop/src/suggest-field/SuggestField.tsx
> +                                  <Image
А просто прокинуть в stub иконки renderProps.items[key].stub не вышло? там же можно урл просто передать если что. или нужно именно чтоб с загрузкой было?

2021-08-06 14:55 UTC, AlekseyShatohin commented on packages/desktop/src/suggest-field/SuggestField.tsx
> +                                  <Image
Тогда иконка размыта будет

2021-08-06 14:57 UTC, AlekseyShatohin commented on packages/desktop/src/suggest-field/SuggestField.tsx
> +                                  <Image
`css={typeof stub === 'string' ? {filter: 'blur(10px)'} : undefined}`

2021-08-06 15:03 UTC, snoosmoomrik approved these changes

2021-08-09 10:43 UTC, dimonka83 requested changes

2021-08-09 10:43 UTC, dimonka83 commented on packages/desktop/src/suggest-field/SuggestFieldOptionModel.ts
> +  stub?: string
давай `stub?: ImageProps['stub']` со всеми вытекающими правками

2021-08-09 10:47 UTC, dimonka83 commented on packages/desktop/src/suggest-field/SuggestFieldOptionModel.ts
> +  stub?: string
а лучше `stub?: string | boolean | ReactNode` даже

2021-08-09 13:43 UTC, Irinaa133 approved these changes

2021-08-09 14:55 UTC, dimonka83 approved these changes

2021-08-10 06:22 UTC, merged