fix(core): select-field-control
qiwi/pijma pull request #435
Opened 2021-08-31 07:37 UTC by Irinaa133

2021-08-31 07:38 UTC, Irinaa133 commented
Если обновлялся пропс value в компоненте, значение select не пересчитывалось

2021-08-31 07:43 UTC, dimonka83 requested changes

2021-08-31 07:43 UTC, dimonka83 commented on packages/core/src/select-field/SelectFieldControl.ts
> +      select: this.findItemIndex(),
через лайфсайкл стейт лучше менять

2021-08-31 09:01 UTC, Irinaa133 commented on packages/core/src/select-field/SelectFieldControl.ts
> +      select: this.findItemIndex(),
сделала

2021-08-31 15:09 UTC, AlekseyShatohin approved these changes

2021-09-01 09:23 UTC, dimonka83 approved these changes

2021-09-01 09:38 UTC, merged