feat: code-field
qiwi/pijma pull request #436
Opened 2021-08-31 15:13 UTC by AlekseyShatohin

2021-09-01 09:02 UTC, Irinaa133 requested changes

2021-09-01 09:32 UTC, AlekseyShatohin commented on packages/core/src/code-field/CodeFieldControl.ts
> +    refs: Array(this.props.length).fill(1).map(() => createRef()),
да, можно так

2021-09-01 09:33 UTC, AlekseyShatohin commented on packages/core/src/code-field/CodeFieldControl.ts
> +      const current = this.state.refs[index]
Если просто ref, то как по мне не совсем очевидно. Потому что используется рефки в трех контекстах: как текущий элемент, как следующий и как предыдущий. И если все рефками назвать, то запутанно выглядит

2021-09-01 09:39 UTC, Irinaa133 commented on packages/core/src/code-field/CodeFieldControl.ts
> +      const current = this.state.refs[index]
может currentRef?

2021-09-01 09:39 UTC, AlekseyShatohin commented on packages/desktop/src/code-field/CodeFieldProps.ts
> +  value: string[]
Например, у нас в сторе хранится value: '123'. Как в компоненте понять, что именно это значит? _123 или 12_3 и так далее. 
Да, согласен, что может быть не очень удобно, что в массиве значения. Можно в стейте хранить массив и отдавать только строку. Но получается, что никак на value повлиять нельзя извне - это не ок. 

Поэтому, сделал метод onReady - он сработает, когда будет полное значение. И в него придет уже value как строка обычная

2021-09-01 09:40 UTC, AlekseyShatohin commented on packages/desktop/src/code-field/CodeField.tsx
> +                  valueSize={5}
fontSize: pxValue(props.valueSize, theme.scale)

2021-09-03 07:46 UTC, snoosmoomrik commented on packages/core/src/code-field/CodeFieldControl.ts
> +    if (this.props.onReady && newValue.find(item => item === '') === undefined) {
Через includes лучше наверное. ```!newValue.includes('')```

2021-09-03 08:33 UTC, snoosmoomrik commented on packages/desktop/src/code-field/CodeField.tsx
> +                  autoFocus={autoFocus && index === 0}
Давай еще на всякий случай ```autocomplete="off"``` добавим

2021-09-06 11:51 UTC, AlekseyShatohin commented
https://user-images.githubusercontent.com/56636950/132213344-3109a15a-9276-40a7-bcdd-779853c04a73.mov

2021-09-06 11:58 UTC, snoosmoomrik commented on packages/desktop/src/code-field/CodeField.tsx
> +        <Pos type="relative" width={1} minHeight={12}>
а зачем minHeight? просто height не подойдет?

2021-09-06 12:25 UTC, Irinaa133 requested changes

2021-09-06 12:25 UTC, Irinaa133 commented on packages/core/src/code-field/CodeFieldControl.ts
> +    e.preventDefault()
в начало лучше

2021-09-06 14:37 UTC, AlekseyShatohin commented on packages/desktop/src/code-field/CodeField.tsx
> +        <Pos type="relative" width={1} minHeight={12}>
Там ошибка может быть на сколько угодно строк, поэтому, лучше наверное minHeight

2021-09-10 13:49 UTC, snoosmoomrik commented on packages/core/src/code-field/CodeFieldControl.ts
> +    if (value.length > 1) {
давай тут еще для number филда ```/^\d$/.test(value)``` проверку добавим?

2021-09-10 14:09 UTC, AlekseyShatohin commented on packages/core/src/code-field/CodeFieldControl.ts
> +    this.onReadyTimeout = setTimeout(() => {
А там в колбэке ts не видит, что уже проверяли на onReady и придется еще раз проверять

2021-09-10 14:10 UTC, Irinaa133 commented on packages/core/src/code-field/CodeFieldControl.ts
> +    this.onReadyTimeout = setTimeout(() => {
мне кажется это лучше, чем лишний таймаут

2021-09-10 14:10 UTC, AlekseyShatohin commented on packages/core/src/code-field/CodeFieldControl.ts
> +    this.onReadyTimeout = setTimeout(() => {
Можно на newValue.includes('') проверить вне таймаута, тогда не будет лишний раз сетиться таймаут

2021-09-10 14:49 UTC, AlekseyShatohin commented on packages/core/src/code-field/CodeFieldControl.ts
> +    if (value.length > 1) {
добавил

2021-09-10 14:50 UTC, AlekseyShatohin commented on packages/core/src/code-field/CodeFieldControl.ts
> +    this.onReadyTimeout = setTimeout(() => {
Сделал двойную проверку. Оставил еще проверку на newValue.includes(''), поскольку значение может измениться, пока таймаут ждет

2021-09-13 06:24 UTC, Irinaa133 commented on packages/desktop/src/code-field/CodeField.md
> +                type="tel"
может по умолчанию сделать type tel?

2021-09-13 07:38 UTC, snoosmoomrik approved these changes

2021-09-14 08:59 UTC, Irinaa133 approved these changes

2021-09-15 08:45 UTC, merged