feat: make autoComplete boolean|string in inputs
qiwi/pijma pull request #453
Opened 2021-11-25 16:43 UTC by oljekechoro

2021-11-25 18:02 UTC, antongolub approved these changes

2021-11-25 18:06 UTC, antongolub requested changes

2021-11-25 18:06 UTC, antongolub commented on packages/core/src/input/BasicInput.tsx
> +        : 'off',
props.autoComplete === 'on' || props.autoComplete === true
   ? 'on'
   : 'off'

2021-11-25 18:34 UTC, dimonka83 commented on packages/desktop/src/password-field/PasswordFieldProps.ts
> +  autoComplete?: BasicInputProps['autoComplete']
я б `boolean | string` сделал, эт так половину пропсов из `BasicInputProps` можно затащить

2021-11-25 18:36 UTC, dimonka83 commented on packages/core/src/input/BasicInput.tsx
> +        : 'off',
@antongolub а где props.autoComplete как string будет тогда?

2021-11-25 18:39 UTC, antongolub commented on packages/core/src/input/BasicInput.tsx
> +        : 'off',
Снаружи пусть и будет string | bool.

2021-11-25 19:49 UTC, oljekechoro commented on packages/core/src/input/BasicInput.tsx
> +        : 'off',
не понял, как мы basicInput'у передадим string? если что, autocomplete, оказывается, может принимать разные значения, не только on/off https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

2021-11-25 19:52 UTC, antongolub commented on packages/core/src/input/BasicInput.tsx
> +        : 'off',
Это меняет дело. Тогда оставляй как есть: string | bool

2021-11-25 20:25 UTC, dimonka83 commented on packages/core/src/input/BasicInput.tsx
> +        : 'off',
`props.autoComplete === true` можно просто `props.autoComplete`, собсна как и было )

2021-11-25 20:42 UTC, oljekechoro commented on packages/desktop/src/password-field/PasswordFieldProps.ts
> +  autoComplete?: BasicInputProps['autoComplete']
а может потихоньку так и затаскивать? чтобы в одном месте все хранилось, все равно же пропса пробрасывается

2021-11-25 20:42 UTC, oljekechoro commented on packages/desktop/src/password-field/PasswordFieldProps.ts
> +  autoComplete?: BasicInputProps['autoComplete']
а, или это в styleguidist'е неправильно отобразится?

2021-11-26 08:49 UTC, antongolub approved these changes

2021-11-26 08:53 UTC, dimonka83 approved these changes

2021-11-26 08:55 UTC, merged