feat: add inputMode to inputs
qiwi/pijma pull request #454
Opened 2021-11-26 16:21 UTC by oljekechoro

2021-11-26 16:27 UTC, antongolub requested changes

2021-11-26 16:27 UTC, antongolub commented on packages/desktop/src/password-field/PasswordFieldProps.ts
> +  inputMode?: BasicInputProps['inputMode']
Do not mix with on* handlers. Move this upper.

2021-11-27 15:11 UTC, dimonka83 approved these changes

2021-11-27 15:54 UTC, antongolub approved these changes

2021-11-27 18:33 UTC, merged