fix(desktop,select): select field cannot be opened by mouse click
qiwi/pijma pull request #470
Opened 2022-03-01 08:42 UTC by Nio-o

2022-03-01 09:03 UTC, dimonka83 requested changes

2022-03-01 09:03 UTC, dimonka83 commented on packages/desktop/src/select-field/SelectField.tsx
> -                rootClose={true}
т.е. при клике вне селекта, селект не пропадает?

2022-03-01 09:27 UTC, Nio-o commented on packages/desktop/src/select-field/SelectField.tsx
> -                rootClose={true}
селект пропадает, потому что срабатывает событие onBlur

2022-03-01 15:31 UTC, dimonka83 approved these changes

2022-03-04 13:46 UTC, antongolub approved these changes

2022-03-04 13:59 UTC, merged