feat: theme link, button, input, tabs
qiwi/pijma pull request #476
Opened 2022-03-23 12:39 UTC by santus20111

2022-03-23 12:48 UTC, antongolub commented on packages/core/src/input/BasicInput.tsx
> +import {useTheme} from '@emotion/react'
It should be wrapped somehow. Like https://github.com/qiwi/pijma/blob/master/packages/core/src/styled.ts

2022-03-23 12:51 UTC, dimonka83 requested changes

2022-03-23 12:51 UTC, dimonka83 commented on packages/core/src/Theme.ts
> +      textColor: {
text: {color: ...} бы

2022-03-23 12:51 UTC, dimonka83 commented on packages/core/src/themes/index.ts
> +import {Theme} from '@emotion/react'
from ../styled

2022-03-24 10:58 UTC, dimonka83 approved these changes

2022-03-24 10:59 UTC, antongolub approved these changes

2022-03-24 11:14 UTC, merged