feat: up deps
qiwi/pijma pull request #525
Opened 2022-08-05 15:17 UTC by dimonka83

update all deps to latest (except webpack)

2022-08-05 17:47 UTC, antongolub approved these changes

2022-08-06 13:13 UTC, antongolub requested changes

2022-08-06 13:13 UTC, antongolub commented on packages/core/package.json
> -    "tslib": "^2.4.0"
tslib?

2022-08-06 17:11 UTC, dimonka83 commented on packages/core/package.json
> -    "tslib": "^2.4.0"
@swc/helpers!

2022-08-06 17:15 UTC, antongolub approved these changes

2022-08-08 06:25 UTC, antongolub approved these changes

2022-08-08 18:02 UTC, oljekechoro approved these changes

2022-08-08 19:09 UTC, merged