wip: allow to pass data attrs
qiwi/pijma pull request #555
Opened 2023-01-18 01:12 UTC by Nio-o

Possible implementation which allows to pass data-* props to components

Examples:

```jsx
<Button stub={true|false} stub-data-testId="stub" data-testId="btn"/>

// When stub=true, stub-data-* will be applied
```

2023-01-27 11:27 UTC, lpk3nny approved these changes
Contract is good enough for pijma2 implementation 😀

2023-01-27 11:39 UTC, antongolub requested changes

2023-01-27 11:39 UTC, antongolub commented on packages/core/src/main/ts/getDataProps.ts
> +  return { data, rest } as any
I'd expect that `getSmth` to return `smth` w/o any boxing. If we need the `rest` fieldset for some exotic case we still can mix it as a non-enumerable prop of `data`.

2023-02-01 11:10 UTC, antongolub submitted a review, later dismissed

2023-02-06 12:15 UTC, snoosmoomrik approved these changes

2023-02-06 12:44 UTC, Oakerin submitted a review, later dismissed

2023-02-08 09:13 UTC, Oakerin approved these changes

2023-02-08 11:41 UTC, antongolub approved these changes

2023-02-08 11:44 UTC, merged